<?php

namespace tests\eu\luige\plagiarism\endpoint\check;

use eu\luige\plagiarism\endpoint\Check;
use tests\eu\luige\plagiarism\RegressionTestCase;

class CheckTest extends RegressionTestCase
{
    /** @var  Check */
    private $check;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }


    public function testSimpleEnqueue()
    {
        $this->API->plagiarismCheck();
    }

}
